repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
    exclude: '\.*conda/.*'
  - id: end-of-file-fixer
  - id: trailing-whitespace
    exclude: '\.txt$|\.tsv$'
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: detect-private-key
  - id: debug-statements
  - id: check-added-large-files

- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.33.0
  hooks:
  - id: markdownlint

- repo: https://github.com/ambv/black
  rev: 23.1.0
  hooks:
  - id: black

- repo: https://github.com/PyCQA/flake8
  rev: "6.0.0"
  hooks:
  - id: flake8
    additional_dependencies: [flake8-bugbear, flake8-quotes]

# Using system installation of pylint to support checking python module imports
- repo: local
  hooks:
  - id: pylint
    name: pylint
    entry: pylint
    language: system
    types: [python]
