[infrastructure]
domain = "populationgenomics.org.au"
dataset_storage_prefix = "cpg-"
budget_currency = "AUD"
reference_dataset = "common"
config_destination = "gs://cpg-config/templates/storage/"
web_url_template = "https://{namespace}-web.populationgenomics.org.au/{dataset}"

#disable_group_memberships = "true"

[infrastructure.gcp]
region = "australia-southeast1"
customer_id = "C010ys3gt"
billing_account_id = '01D012-20A6A2-CBD343'
billing_project_id = 'billing-admin-290403'
budget_notification_pubsub = "projects/billing-admin-290403/topics/budget-notifications"
reference_bucket_name = "cpg-reference"
config_bucket_name = "cpg-config"

[infrastructure.azure]
region = "australiaeast"
tenant = "a744336e-0ec4-40f1-891f-6c8ccaf8e267"

[infrastructure.hail.gcp]
wheel_bucket_name = "cpg-hail-ci"

[infrastructure.analysis_runner.gcp]
project = "analysis-runner"
cloud_run_instance_name = "server"
server_machine_account = "analysis-runner-server@analysis-runner.iam.gserviceaccount.com"
logger_machine_account = "sample-metadata@analysis-runner.iam.gserviceaccount.com"
container_registry_name = "images"

[infrastructure.web_service.gcp]
server_machine_account = "web-server@analysis-runner.iam.gserviceaccount.com"

[infrastructure.access_group_cache]
process_machine_account = "access-group-cache@analysis-runner.iam.gserviceaccount.com"

[infrastructure.notebooks.gcp]
project = "notebooks-314505"

[infrastructure.cromwell.gcp]
access_group_id = "groups/03cqmetx2922fyu"
runner_machine_account = "cromwell-runner@cromwell-305305.iam.gserviceaccount.com"

[infrastructure.sample_metadata.gcp]
project = "sample-metadata"
service_name = "sample-metadata-api"
machine_account = "sample-metadata-api@sample-metadata.iam.gserviceaccount.com"
