common:
  archive_age: 90
  components:
    azure:
    - storage
    - container-registry
    gcp:
    - storage
    - container-registry
  create_container_registry: 'true'
  deploy_locations:
  - gcp
  - azure
  enable_release: false
  gcp:
    project: cpg-common