name: Lint
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Authenticate to GitHub
        env:
          TOKEN: ${{ secrets.SAMPLE_METADATA_REPO_TOKEN }}
        run: |
          git config --global credential.helper store
          echo "$TOKEN" | git credential approve

      - name: Install packages
        run: |
          pip install \
              -r requirements-dev.txt \
              -r cpg_infra/billing_aggregator/aggregate/requirements.txt \
              -r storage_visualization/requirements.txt

      - name: Run tests using coverage
        run: |
          coverage run -m unittest discover -s test/
          rc=$?
          coverage xml

          echo "rc=$rc" >> $GITHUB_OUTPUT

# configure this later
#      - name: "Upload coverage report"
#        uses: codecov/codecov-action@v2
#        with:
#          files: ./coverage.xml

      - name: pre-commit
        run: pre-commit run --all-files

      - name: Fail if tests are not passing
        if: ${{ steps.runtests.outputs.rc != 0 }}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Unit tests failed with rc = ${{ steps.runtests.outputs.rc }}')
