name: Lint + Test
on:
  pull_request:
    types: ["opened", "synchronize"]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install packages
        run: |
          pip install \
              -r requirements-dev.txt \
              -r cpg_infra/billing_aggregator/aggregate/requirements.txt \
              -r storage_visualization/requirements.txt

      - name: pre-commit
        run: pre-commit run --all-files

      - name: Run tests using coverage
        id: runtests
        run: |
          coverage run -m xmlrunner discover -v -s test/
          rc=$?
          coverage xml

          echo "rc=$rc" >> $GITHUB_OUTPUT

      - name: "Upload coverage report"
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }} # required

      - name: Fail if tests are not passing
        if: ${{ steps.runtests.outputs.rc != 0 }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('Unit tests failed with rc = ${{ steps.runtests.outputs.rc }}')

      - name: Test Summary
        uses: test-summary/action@v2
        if: always()
        with:
          name: Test Summary
          paths: "TEST-*.xml"
          output: test-summary.md

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/linux@v2
        if: always()
        with:
          name: Unit Test Results
          files: |
            TEST-*.xml

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()                  # run this step even if previous step failed
        with:
          name: Test Results          # Name of the check run which will be created
          path: TEST-*.xml            # Path to test results
          reporter: swift-xunit       # Format of test results
