name: Lint
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install packages
        run: |
          pip install \
              -r requirements-dev.txt \
              -r cpg_infra/billing_aggregator/aggregate/requirements.txt \
              -r storage_visualization/requirements.txt

      - name: pre-commit
        run: pre-commit run --all-files
