name: Lint + Test
on:
  pull_request:
    types: ["opened", "synchronize"]

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install packages
        run: |
          pip install \
              -r requirements-dev.txt \
              -r cpg_infra/billing_aggregator/aggregate/requirements.txt \
              -r storage_visualization/requirements.txt

      - name: Run tests using coverage
        id: runtests
        run: |
          coverage run -m unittest discover -s test/
          rc=$?
          coverage xml

          echo "rc=$rc" >> $GITHUB_OUTPUT

      - name: "Upload coverage report"
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml

      - name: pre-commit
        run: pre-commit run --all-files

      - name: Fail if tests are not passing
        if: ${{ steps.runtests.outputs.rc != 0 }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('Unit tests failed with rc = ${{ steps.runtests.outputs.rc }}')
