name: Preview

on:
  pull_request:
    types: ["opened", "synchronize"]

permissions:
  id-token: write
  pull-requests: write
  contents: read

jobs:
  preview:
    runs-on: ubuntu-latest
    # required for Azure
    environment: production

    steps:
      # Checkout this repository (cpg-infrastructure).
      - uses: actions/checkout@v3

      # Checkout the private repository (cpg-infrastructure-private).
      - uses: actions/checkout@v3
        with:
          repository: populationgenomics/cpg-infrastructure-private
          path: cpg-infrastructure-private
          ssh-key: ${{ secrets.INFRA_PRIVATE_DEPLOY_TOKEN }}

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip" # caching pip dependencies

      - name: "Authenticate to GitHub"
        env:
          TOKEN: ${{ secrets.SAMPLE_METADATA_REPO_TOKEN }}
        run: |
          git config --global credential.helper store
          echo "$TOKEN" | git credential approve

      - id: "auth-azure"
        name: "Authenticate to Azure Cloud"
        uses: azure/login@v1
        with:
          # for workflow identity federation
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - id: "google-cloud-auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: "projects/1051897107465/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "pulumi@cpg-common.iam.gserviceaccount.com"

      - id: "google-cloud-sdk-setup"
        name: "Set up Cloud SDK"
        uses: google-github-actions/setup-gcloud@v1

      - run: |
          pip install --upgrade pip
          pip install .

      - uses: pulumi/actions@v4
        with:
          command: preview
          work-dir: cpg-infrastructure-private/
          stack-name: production
          cloud-url: gs://cpg-pulumi-state/
          comment-on-pr: true
          # No diff for cpg-infrastructure to avoid leaking personal details
          diff: false
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
          ARM_USE_OIDC: "true"
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_LOCATION_NAME: "australiaeast"
