name: Security Checks

on:
  workflow_dispatch:
  push:

jobs:
  pip-audit:
    runs-on: ubuntu-latest
    name: Pip Audit
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d #v10.0.1
        with:
          activate-environment: true
          enable-cache: false
          version: 0.11.21 #uv version

      - name: Install packages
        run: uv sync --upgrade-package metamist-infrastructure

      - uses: pypa/gh-action-pip-audit@1220774d901786e6f652ae159f7b6bc8fea6d266 #v1.1.0
        with:
          virtual-environment: .venv
          summary: true
